Repository betagouv/leximpact-client, pull requests merged in 2019-06, with the labels that each got.

#11 Rend l'url de l'API modifiable
  components/Article.jsx
  components/Drawer.jsx
  components/Grid.jsx
  components/Header.jsx
  components/Impact.jsx
  components/RecettesCard.jsx
  components/Reformeur.jsx
  components/SelectControl.jsx
  components/SimpleCard.jsx
  components/TabMobile.jsx
  components/Tag.jsx
  next.config.js
  package-lock.json
  package.json
  pages/index.jsx
Labels: kind:devops, type:client

#13 Ajoute de l'intégration en continu
  .circleci/config.yml
Labels: kind:devops, type:client

#14 Add divider
  components/SimpleCard.jsx
Labels: kind:improvement, type:client

#15 Bar Chart + background image + bugs
  components/Article.jsx
  components/ArticleHeader.jsx
  components/BarChart.jsx
  components/CarteEtat.jsx
  components/Header.jsx
  components/Impact.jsx
  components/RecettesCard.jsx
  components/Reformeur.jsx
  components/SimpleCard.jsx
  next.config.js
  package-lock.json
  package.json
  static/images/decile1.png
  static/images/decile10.png
  static/images/decile2.png
  static/images/decile3.png
  static/images/decile4.png
  static/images/decile5.png
  static/images/decile6.png
  static/images/decile7.png
  static/images/decile8.png
  static/images/decile9.png
  styles/chart.scss
  styles/index.scss
Labels: kind:bug, kind:improvement, kind:solution, type:client

#18 Refactoring Header component
  .flowconfig
  babel.config.js
  components/Article.jsx
  components/ArticleHeader.jsx
  components/BarChart.jsx
  components/CarteEtat.jsx
  components/Header.jsx
  components/Impact.jsx
  components/RecettesCard.jsx
  components/Reformeur.jsx
  components/SimpleCard.jsx
  components/header/header-container.jsx
  components/header/home.jsx
  components/header/links.jsx
  components/header/login.jsx
  components/header/menu-container.jsx
  components/header/menu-reducer.jsx
  components/header/menu.jsx
  components/header/signup.jsx
  jest.config.js
  next.config.js
  package-lock.json
  package.json
  pages/index.jsx
  postcss.config.js
  tests/components/header/home.test.jsx
  tests/components/header/links.test.jsx
  tests/components/header/login.test.jsx
  tests/components/header/menu-reducer.test.js
  tests/components/header/menu.test.jsx
  tests/components/header/signup.test.jsx
  tests/enzyme.config.js
Labels: kind:refactoring, type:client
